version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./test:/var/lib/mysql
      - ./BD:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PiZhop
      MYSQL_USER: jouad
      MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  web:
    build:
      context: .
    depends_on:
      - db
    image: tomcat:9.0
    volumes:
      -  ./ProyectoGlobal-PiZhop.war:/usr/local/tomcat/webapps/ProyectoGlobal-PiZhop.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PiZhop
      MYSQL_USER: jouad
      MYSQL_PASSWORD: 1234
